name: 'CI - Backend'

on:
  push:
    branches:
      - master
      - dev
      - 'releases/**'
    paths:
      - 'RetrospectiveExtension.Backend/**'
  pull_request:
    branches:
      - master
      - dev
      - 'releases/**'
    paths:
      - 'RetrospectiveExtension.Backend/**'
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
