name: 'CI - Backend'

on:
  push:
    branches:
      - master
      - dev
      - 'releases/**'
  pull_request:
    branches:
      - master
      - dev
      - 'releases/**'
  workflow_dispatch:

jobs:
  build:
    name: Backend - Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '.github/**'
              - 'RetrospectiveExtension.Backend/**'
              - 'RetrospectiveExtension.Backend.Tests/**'

      - if: steps.changes.outputs.src == 'true'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.404'

      - if: steps.changes.outputs.src == 'true'
        run: |
          dotnet restore
          dotnet build
        name: Build
        working-directory: 'RetrospectiveExtension.Backend'

      - if: steps.changes.outputs.src == 'true'
        run: |
          dotnet test
        name: Test
        working-directory: 'RetrospectiveExtension.Backend.Tests'
