name: 'CI - Backend'

on:
  push:
    branches:
      - master
      - dev
      - 'releases/**'
  pull_request:
    branches:
      - master
      - dev
      - 'releases/**'
  workflow_dispatch:

jobs:
  build:
    name: Backend - Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '.github/**'
              - 'RetrospectiveExtension.Backend/**'
              - 'RetrospectiveExtension.Backend.Tests/**'

      - if: steps.changes.outputs.src == 'true'
        name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - if: steps.changes.outputs.src == 'true'
        name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - if: steps.changes.outputs.src == 'true'
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
