name: 'CI - Frontend'

on:
  push:
    branches:
      - master
      - dev
      - 'releases/**'
  pull_request:
    branches:
      - master
      - dev
      - 'releases/**'
  workflow_dispatch:

jobs:
  build:
    name: Frontend - Build and Test  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '.github/**'
              - 'RetrospectiveExtension.Frontend/**'

      - if: steps.changes.outputs.src == 'true'
        run: |
          npm install
          npm run lint
          npm run build:p
          npm run test
          npm run pack:p
        name: Build and Test
        working-directory: 'RetrospectiveExtension.Frontend'

      - if: steps.changes.outputs.src == 'true'
        name: Upload test report
        uses: dorny/test-reporter@v1.5.0
        with:
          name: JEST Tests
          path: reports/jest-*.xml
          reporter: jest-junit
          working-directory: 'RetrospectiveExtension.Frontend'
