name: 'CI - Frontend'

on:
  push:
    branches:
      - master
      - dev
      - 'releases/**'
    paths-ignore:
      - 'RetrospectiveExtension.Backend/**'
  pull_request:
    branches:
      - master
      - dev
      - 'releases/**'
    paths-ignore:
      - 'RetrospectiveExtension.Backend/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build and Test

    steps:
    - uses: actions/checkout@v2
      name: Check out repository

    - run: |
        echo "Testing Frontend"
      name: Build and Test
      working-directory: 'RetrospectiveExtension.Frontend'
