name: 'CI - Frontend'

on:
  push:
    branches:
      - master
      - dev
      - 'releases/**'
    paths-ignore:
      - 'RetrospectiveExtension.Backend/**'
  pull_request:
    branches:
      - master
      - dev
      - 'releases/**'
    paths-ignore:
      - 'RetrospectiveExtension.Backend/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build and Test

    steps:
    - uses: actions/checkout@v2
      name: Check out repository

    - run: |
        npm install
        npm run lint
        npm run build:p
        npm run test
        npm run pack:p
      name: Build and Test
      working-directory: 'RetrospectiveExtension.Frontend'

    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()
      with:
        name: JEST Tests
        path: reports/jest-*.xml
        reporter: jest-junit
        working-directory: 'RetrospectiveExtension.Frontend'
