name: pr

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd "RetrospectiveExtension.Frontend" && npm install && npm run lint && npm run build:p && npm run pack:p