name: PRWorkflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd "RetrospectiveExtension.Frontend"
    - run: npm install
    - run: npm run lint
    - run: npm run build
    - run: npm run pack
